# This is a basic workflow to help you get started with Actions

name: Create master to develop Pull Requests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Check PR exsitance
        id: pull_request_exists
        run: |
          echo "::set-output name=count::$(gh pr list --head master -B develop | wc -l)"
      
      - name: Create a PR
        if: ${{ steps.pull_request_exists.outputs.count == 0 }}
        run: |
          gh pr create -B develop --head master -t "Update develop from master" -b ""
